import DisplayIf from '@/components/DisplayIf';
import { CardHeader, CardTitle, CardDescription, CardContent, Card } from '@/components/ui/card';
import { Table, TableBody, TableCaption, TableCell, TableFooter, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { cn } from '@/lib/utils';
import { LogLevel } from '@/types/log';
import { ExecutionLog } from '@prisma/client';
import React from 'react';

type LogViewerProps = {
	logs: ExecutionLog[] | undefined;
};

function LogViewer({ logs }: LogViewerProps) {
	return (
		<>
			<DisplayIf condition={!logs || logs.length === 0}>{null}</DisplayIf>
			<DisplayIf condition={logs?.length !== 0}>
				<Card>
					<CardHeader className="rounded-lg rounded-b-none border-b py-4 bg-gray-50 dark:bg-background">
						<CardTitle className="text-base">Logs</CardTitle>
						<CardDescription className="text-sm text-muted-foreground">Logs generated by this phase</CardDescription>
					</CardHeader>
					<CardContent className="p-0">
						<Table>
							<TableHeader className="text-muted-foreground text-sm">
								<TableRow>
									<TableHead>Time</TableHead>
									<TableHead>Level</TableHead>
									<TableHead>Message</TableHead>
								</TableRow>
							</TableHeader>
							<TableBody>
								{logs?.map((log) => (
									<TableRow key={log.id} className="text-muted-foreground">
										<TableCell width={190} className="text-xs text-muted-foreground p-0.5 pl-4">
											{log.timestamp.toLocaleString()}
										</TableCell>
										<TableCell
											width={80}
											className={cn(
												'uppercase text-xs font-bold p-1 pl-4',
												(log.logLevel as LogLevel) === 'error' && 'text-destructive',
												(log.logLevel as LogLevel) === 'info' && 'text-primary'
											)}
										>
											{log.logLevel}
										</TableCell>
										<TableCell className="text-sm flex-1 p-1 pl-4">{log.message}</TableCell>
									</TableRow>
								))}
							</TableBody>
						</Table>
					</CardContent>
				</Card>
			</DisplayIf>
		</>
	);
}

export default LogViewer;
