import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import DisplayIf from '@/components/DisplayIf';
import { Input } from '@/components/ui/input';

type ParameterViewerProps = {
	title: string;
	subTitle: string;
	paramsJson: string | null;
};

const ParameterViewer = ({ title, subTitle, paramsJson }: ParameterViewerProps) => {
	let params;
	try {
		params = paramsJson ? JSON.parse(paramsJson) : {};
	} catch (error) {
		console.error('Invalid JSON format', error);
		params = {};
	}
	return (
		<Card>
			<CardHeader className="rounded-lg rounded-b-none border-b py-4 bg-gray-50 dark:bg-background">
				<CardTitle className="text-base">{title}</CardTitle>
				<CardDescription className="text-sm text-muted-foreground">{subTitle}</CardDescription>
			</CardHeader>
			<CardContent className="py-4">
				<div className="flex flex-col gap-2">
					<DisplayIf condition={Object.keys(params).length === 0}>
						<p className="text-sm">No parameters generated by this phase</p>
					</DisplayIf>
					<DisplayIf condition={Object.keys(params).length > 0}>
						{Object.entries(params).map(([key, value]) => (
							<div key={key} className="flex justify-between items-center space-y-1">
								<p className="text-sm text-muted-foreground flex-1 basis-1/3">{key}</p>
								<Input readOnly className="flex-1 basis-2/3" value={value as string} />
							</div>
						))}
					</DisplayIf>
				</div>
			</CardContent>
		</Card>
	);
};

export default ParameterViewer;
